name: Build and release

on:
  push:
    branches:
      - master # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly

      - name: Build Rust Project
        run: cargo build --release
        working-directory: ./webrtc_stream_server

      - name: Create Release
        id: create_release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: webrtc_stream_server/target/release/webrtc_stream_server
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true